### ISSUE TITLE
Features missing?

### ISSUE THREAD

**Issue by subsoap** [defold/extension-webmonetization#1]
User needs to be able to get some data during webmonetization.EVENT_START and webmonetization.EVENT_PROGRESS

I think there should be data like 
```
       paymentPointer,
        requestId,
        amount,
        assetCode,
        assetScale,
        receipt
```
Within event.detail?

Then we can check amounts and validate the payment on a server.

**Comment by subsoap** [comment]
https://webmonetization.org/docs/api/#monetizationprogress

So with monetizationprogress it should probably return the webmonetization.EVENT_PROGRESS and a table of the event.detail contents. Same with start although it has less stuff in the detail.

The callback could then be like

```
	webmonetization.set_listener(function(self, event, detail)
		if event == webmonetization.EVENT_PENDING then
			print("The user is trying to make a first payment")
		elseif event == webmonetization.EVENT_START then
			print("The user has started paying")
			pprint(detail)
		elseif event == webmonetization.EVENT_PROGRESS then
			print("The user is still paying")
			pprint(detail)
		elseif event == webmonetization.EVENT_STOP then
			print("The user has stopped paying")
		end
	end)
```

**Comment by britzl** [comment]
Good point! I'll look into this!

**Comment by britzl** [comment]
Added support for event details:

https://github.com/defold/extension-webmonetization/releases/tag/1.0.0
